### ISSUE TITLE
URGENT: jurors unable to see all images in final rating round

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#101]
We have just started our final, ranking, round in the UK, which is supposed to have 197 images. Our judges are able to see only 100, regardless of the chosen thumbnail size.

If this could be looked at quickly I'd appreciate it, as our judges have only this weekend to complete the round prior to an in-person meeting next week.  We may now be in real danger of not being able to complete by the end of the month.

Thanks all!

**Comment by mahmoud** [comment]
Hi Michael! The ranking round is not intended for rounds with over 50 images, and used to have messaging to this effect. The algorithm and UI will simply not scale to a group of that size, and I'm sure research into voting/ballots would agree. I would strongly recommend running a yes/no round with the question: "Does this image belong in the final round?" Would that be possible?

**Comment by MichaelNMaggs** [comment]
Ugh!  This is so frustrating. When I was a juror with Wiki Loves Africa we were asked to rank with much bigger rounds than this.  That's why we did it this way now.  Presumably the program has since been restricted to lower numbers.  It's embarrassing to say the least to have asked three professional photographers to judge the final and now have to tell them the tool does not support what they've been asked to do.

**Comment by MichaelNMaggs** [comment]
I will have to see what we can do tomorrow now.

**Comment by mahmoud** [comment]
I'm very sorry about the confusion. The fact is that people will not meaningfully and carefully consider every single relationship between images when the number is that high. That means people hit the button without fully sorting the set, and we end up with a jumbled opinion. Everyone will have their faves at the top, but the likelihood for overlap in that top ten is extremely limited, meaning that when the rankings are combined, the resulting ranking bears very little resemblance to a consensus. Images may win by middle-of-the-pack-ness or by sheer chance (due to the randomization of each ballot). If they made it this far I'm sure they are nice, but they may not compete well in the International Round.

We will have to do better do document these nuances in the upcoming Montage User Manual. Extend my apologies for the inconvenience to the esteemed judges. It sounds like quite a lineup! I do hope the final results represent all the excellent work you've put into this, and we'll work harder to make this better explained in the future.

**Comment by MichaelNMaggs** [comment]
The judges are asked to sort the top 10 only and to leave the rest.  We're actually only interested in their top 10s.  Tomorrow I'll cancel this round and do a new yes/no round. Thanks for the prompt responses anyway.
