### ISSUE TITLE
Automatically recuse from voting on your own photos

### ISSUE THREAD

**Issue by brittag** [hatnote/montage#181]
I'm judging WLM US, and I got amusingly lucky: a photo I submitted was in my own judging queue! I gave myself a mediocre score because it was a mediocre photo, but it'd be nice to automatically not see any photos I've uploaded (when my username matches the Commons username that uploaded the photo).

**Comment by mahmoud** [comment]
Haha, you could have been even luckier! ;) Joking aside, good on you for submitting photos, taking the time to judge, and raising the issue.

So Montage has an option to automatically disqualify photos by judges (accessible to coordinators at round creation), but not one to assign around them. 

Thinking about it, assigning around could be hard to implement, due to edge cases, but that's not the main issue. More importantly assigning around such conflicts of interest would only defer the scenario, because judges must rank all photos in the final round. So I guess, expectations-wise, do folks expect judges of early rounds might be able to win top spots later? Or do most communities expect judges of all levels recuse their entries from winning? 

If the latter, probably the round creator should have ticked a box in the beginning. We could make it ticked by default if that's overwhelmingly the case. I'll need to take this back to the rest of the team and see how they'd like to proceed.

Thanks again!

**Comment by brittag** [comment]
Good questions, and I agree that finding out about expectations from a range of people would be helpful!

I'd expect my own photos to be not shown to me unless they _have_ to. (In other words, if the other judges liked my photos enough to vote them into the final round, it's ok to show me my photos in the final round for ranking.) I'd also be totally fine with my photos being entirely disqualified from the judging - it'd make sense to me to check that checkbox by default.

**Comment by brittag** [comment]
Looking back at this old thing I filed, I think the existing option to automatically disqualify photos by judges is sufficient. If a round creator doesn't enable that option, and a judge's photo gets to the last rounds, the judging team will figure it out and disqualify the image appropriately.
