### ISSUE TITLE
Decreasing quorum value for WLE-France

### ISSUE THREAD

**Issue by leilaz** [hatnote/montage#47]
WLE France needs your help. In their round 2, they have removed one out of five jurors and their quorum was set to 5. Can you help them by reducing the quorum to 4, please? This will help them close their round 2. Thanks! :)

**Comment by mahmoud** [comment]
We still don't have built-in support for quorum reduction in Montage due to the difficulties around discarding votes. 

For a little more context, in our earlier discussions we talked about the case where a juror is swapped out and decided that we didn't want the new juror to have to redo all of the previous juror's work. For the new version of Montage @slaporte and I have discussed some possible scenarios for supporting this. 

I think the most common scenario is probably the one described here: a juror dropped out and the organizers would like to drop all that user's votes _and_ drop the quorum. That's a little less ambiguous than reducing the quorum on its own. So we can probably make the new version do it.

As for the current situation, maybe we can belt out an admin tool? No guarantee it would be faster than finding a substitute juror though.

**Comment by leilaz** [comment]
Thanks @mahmoud . Finding a new juror doesn't seem to be an option on their end given the timelines. I'm wondering: in this specific case, if finding a workaround ends up being too expensive on your end (taking your time from other issues), we should probably just extract the raw data from the database and give those to the coordinator. This should be possible, right? :)

**Comment by leilaz** [comment]
@mahmoud I extracted the final round results and gave them to Jules. They are good to go. resolving this issue.

**Comment by mahmoud** [comment]
Great, thanks for the update!
