### ISSUE TITLE
Add ".csv" to results filename

### ISSUE THREAD

**Issue by MichaelNMaggs** [hatnote/montage#79]
After downloading the results as a coordinator, my Mac refuses to recognise the output file format unless I manually add ".csv" at the end of the filename.

Could .csv be added automatically?

**Comment by yarl** [comment]
Sounds like Safari. It's a long running issue generally.

**Comment by MichaelNMaggs** [comment]
I use Firefox for Mac. Tried to open the file in Numbers

**Comment by slaporte** [comment]
What version of Firefox? We're saving the file as montage-<round name>-<date>.csv. It's working fine with the extension for me in Chrome. I can double check if it's a browser issue or a problem with our encoding or something.

**Comment by MichaelNMaggs** [comment]
Firefox 56.0.

**Comment by mahmoud** [comment]
Yeah, I've just repro'd this in 55. Investigating.

**Comment by mahmoud** [comment]
OK I believe the problem here is that [here](https://github.com/hatnote/montage/blob/2405e9db6c45b905a503ecff2d31e9cda826446f/montage/admin_endpoints.py#L701), the round name is being formatted into the filename without being sluggified, and the round name contains spaces. Chrome must be OK with spaces in the filename, whereas Firefox wants it quoted. I'm going to switch this to call `slugify()` on the filename, which will turn all spaces into underscores and we'll all live happily ever after :)

**Comment by atsirlin** [comment]
Firefox has developed since then. My v.66 does the proper export and adds the csv extension. Is there anything else to be done here?

**Comment by MichaelNMaggs** [comment]
Sounds as if the Firefox bug I reported has gone away, then.

**Comment by lgelauff** [comment]
seems resolved. Please reopen if not.
